project:
  type: website
  output-dir: docs

website:
  title: "Activated Sludge Model"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Linear Regressions"
        contents:
          - linear_regressions.qmd
      - section: "Environmental Parameter Analysis"
        contents:
          - environmental_parameter_analysis.qmd
      - section: "Exploratory Analysis"
        contents:
          - trend_decomposition.qmd
          - fourier_transform.qmd
      - section: "Observable Patterns"
        contents:
          - correlation_matrix.qmd
          - indicator_species_plots.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

