project:
  type: website
  output-dir: docs

website:
  title: "Activated Sludge Model"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - environmental_parameter_analysis.qmd
      - correlation_matrix.qmd
      - fourier_transform.qmd
      - trend_decomposition.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

