project:
  type: website
  output-dir: docs
  render:
      - correlation_matrix.qmd
      - fourier_transform.qmd

website:
  title: "Activated Sludge Model"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - correlation_matrix.qmd
      - fourier_transform.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

