project:
  type: website
  output-dir: docs

website:
  title: "Activated Sludge Model"
  navbar:
    background: primary
    search: true
    sidebar:
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - href: index.qmd
          text: Home
        - href: exploring_parameters.qmd
          text: Exploring Input and Output Parameters
          contents:
            - environmental_parameter_analysis.qmd
            - correlation_matrix.qmd
            - fourier_transform.qmd
            - trend_decomposition.qmd
            - linear_regressions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

