project:
  type: website
  output-dir: docs
  render:
      - correlation_matrix.qmd
      - fourier_transform.qmd


website:
  title: "Activated Sludge Model"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - correlation_matrix.qmd
      - fourier_transform.qmd
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

